'use client'

import React from 'react'
import { FileBarChart, Download } from 'lucide-react'

interface ReportItem {
  id: string
  name: string
  size: string
  date: string
  category: string
}

const mockReports: ReportItem[] = [
  {
    id: 'rep-1',
    name: 'Silicon District Q2 Engagement Statistics.pdf',
    size: '4.8 MB',
    date: 'Just now',
    category: 'COGNITIVE USAGE'
  },
  {
    id: 'rep-2',
    name: 'Midwest High Schools Standards Mapping G.pdf',
    size: '12.4 MB',
    date: '2 days ago',
    category: 'CORE STANDARDS'
  },
  {
    id: 'rep-3',
    name: 'AI Prompt Optimization & Cost Audit June.pdf',
    size: '2.1 MB',
    date: '7 days ago',
    category: 'FINANCIAL / API TECH'
  },
  {
    id: 'rep-4',
    name: 'Crescent Valley Onboarding Feedback Analysis.pdf',
    size: '6.2 MB',
    date: '14 days ago',
    category: 'FEEDBACK INSIGHTS'
  }
]

const ReportsPage = () => {
  const handleDownload = (name: string) => {
    alert(`Starting secure download for: ${name}`)
  }

  return (
    <div className="flex flex-col gap-6 w-full animate-in fade-in duration-300">
      
      {/* Header Info Card */}
      <div className="rounded-xl border border-gray-100 bg-white p-5 shadow-sm text-left">
        <div className="flex items-start gap-3.5">
          <div className="h-9 w-9 rounded-lg bg-orange-50 flex items-center justify-center shrink-0">
            <FileBarChart className="h-4.5 w-4.5 text-main" />
          </div>
          <div>
            <h3 className="text-base font-bold text-title">Analytical Dossier Repository</h3>
            <p className="text-xs font-semibold text-gray-400 mt-1">
              Review, analyze, and retrieve detailed system logs and school metrics generated by the dashboard.
            </p>
          </div>
        </div>
      </div>

      {/* Grid of Dossier Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {mockReports.map((report) => (
          <div 
            key={report.id}
            className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm hover:shadow-md transition-shadow duration-200 flex items-center justify-between gap-4"
          >
            {/* Left Content (File Icon + Details) */}
            <div className="flex items-center gap-3.5 min-w-0">
              <div className="h-10 w-10 rounded-lg bg-orange-50 flex items-center justify-center shrink-0 shadow-inner">
                <FileBarChart className="h-5 w-5 text-main" />
              </div>
              
              <div className="flex flex-col text-left min-w-0">
                <h4 className="text-xs font-bold text-title truncate leading-normal" title={report.name}>
                  {report.name}
                </h4>
                
                <div className="flex flex-wrap items-center gap-2 mt-1.5 text-[10px] font-semibold text-gray-400">
                  <span>{report.size}</span>
                  <span>•</span>
                  <span>{report.date}</span>
                  <span>•</span>
                  <span className="bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded-md text-[8px] font-extrabold tracking-wide uppercase">
                    {report.category}
                  </span>
                </div>
              </div>
            </div>

            {/* Right Action */}
            <button
              onClick={() => handleDownload(report.name)}
              className="text-xs font-bold text-main hover:text-main-dark hover:underline transition-colors shrink-0 flex items-center gap-1 cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download</span>
            </button>

          </div>
        ))}
      </div>

    </div>
  )
}

export default ReportsPage